apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  serviceAccountName: podinfo-team
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: podinfo
      version: 6.5.3
  values:
    # Service should be disabled when using Flagger
    service:
      enabled: false
    ingress:
      enabled: true
      className: nginx
    hpa: 
      enabled: true
  interval: 5m
  install:
    remediation:
      retries: 3
